name: Python CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: pip install uv
      - name: Install deps
        run: uv pip install -e ./server ruff mypy pytest
      - name: Lint
        run: uv run ruff check server
      - name: Type
        run: uv run mypy server
      - name: Test
        run: uv run pytest -q