interval: 5.0
serial:
  port: /dev/ttyUSB0
  baud: 115200
max_lines: 12

# Order matters; first entries appear first on LCD
sensors:
  - name: CPU
    provider: cpu
    enabled: true
  - name: GPU0
    provider: gpu
    enabled: true

# Commands reserved for Phase 6
#commands:
#  - id: 1
#    label: Shutdown
#    exec: "sudo shutdown -h now"
