interval: 1.0
serial:
  port: /dev/ttyUSB0
  baud: 115200
max_lines: 12

# Order matters; first entries appear first on LCD
sensors:
  - name: CPU
    provider: cpu
    enabled: true
  - name: GPU
    provider: gpu
    enabled: true
  # Join Pkg (CPU package) and motherboard ACPI temp on one line
  - name: T
    provider: join
    enabled: true
    join:
      - name: Pkg
        provider: temp
        params:
          chip: coretemp
          label: "Package id 0"
      - name: MB
        provider: temp
        params:
          chip: acpitz
          label: temp1

  # Join NVMe Sensor 1 and Sensor 2 on one line
  - name: NVMe
    provider: join
    enabled: true
    join:
      - name: "1:"
        provider: temp
        params:
          chip: nvme
          label: "Sensor 1"
      - name: "2:"
        provider: temp
        params:
          chip: nvme
          label: "Sensor 2"

# Commands for Phase 6 (server protocol only; execution disabled by default)
commands:
  - id: "1"
    label: Shutdown
    exec: "sudo -n shutdown -h now"
  - id: "2"
    label: Reboot
    exec: "sudo -n shutdown -r now"
  - id: "3"
    label: Command 3
    exec: "/usr/bin/echo example"
  - id: "98"
    label: "Something Else 1"
    exec: "/usr/bin/true"
  - id: "99"
    label: "Something Else 2"
    exec: "/usr/bin/false"
